# Generated by Django 3.2 on 2021-08-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('nominal', models.PositiveSmallIntegerField()),
                ('parent_code', models.CharField(max_length=32)),
                ('iso_num', models.CharField(max_length=16)),
                ('iso_char', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='SumDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_1', models.DateField()),
                ('date_2', models.DateField()),
                ('sum_date_1', models.FloatField(blank=True, default=0, null=True)),
                ('sum_date_2', models.FloatField(blank=True, default=0, null=True)),
                ('sum_date', models.FloatField(blank=True, default=0, null=True)),
                ('main_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_currency', to='currency.currency')),
            ],
        ),
    ]
