# Generated by Django 3.2 on 2021-08-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumdate',
            name='date_1',
        ),
        migrations.RemoveField(
            model_name='sumdate',
            name='date_2',
        ),
        migrations.RemoveField(
            model_name='sumdate',
            name='main_currency',
        ),
    ]
